AVI-5: create UI template for dashboard(html and css only)
harry-olabs/avi-hub pull request #12
Opened 2023-06-12 22:01 UTC by Doyin02

### What does this PR do

This is the UI for the dashboard created with only html and css.

Closes #5

### How should it be tested

Go to your local development, navigate to template, Inside the template you will find a file named dashboard.html and also inside the template, there is a folder named styles, navigate into the styles and also open up the dashboard.css
Enter the dashboard.html file, right click on your mouse and run with live server. 

### Screenshots

![Screenshot (21)](https://github.com/harry-olabs/avi-hub/assets/80858126/0a71dd5a-e02e-497d-a6b9-24f0123126d3)

2023-06-14 08:55 UTC, harry-olabs commented
@Doyin02 would've been nice if you shared a screenshot on the new look.

2023-06-14 08:56 UTC, Doyin02 commented
will do so now


On Wed, Jun 14, 2023 at 9:55 AM Harry ***@***.***> wrote:

> @Doyin02 <https://github.com/Doyin02> would've been nice if you shared a
> screenshot on the new look.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/harry-olabs/avi-hub/pull/12#issuecomment-1590770470>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATI4YDWWJMHHOS6P3WUTG4DXLF4BFANCNFSM6AAAAAAZD7ONU4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-14 09:19 UTC, harry-olabs commented
@Doyin02, it is looking good, just requires some improvements. 
I have attached screenshots below to give you an idea what we are trying to achieve.

| Design | Skeleton |
|--------|----------|
|   <img width="1478" alt="Screenshot 2023-06-14 at 02 12 32" src="https://github.com/harry-olabs/avi-hub/assets/135703492/710ba6cf-b169-4283-89b1-a111abf409a3"> |  <img width="1478" alt="Screenshot 2023-06-14 at 11 13 13" src="https://github.com/harry-olabs/avi-hub/assets/135703492/dc4d6e52-1044-4ce7-8cc3-b22bdc422a33"> |

2023-06-14 09:20 UTC, Doyin02 commented
The before and after of the dashboard

| Before | After |
| -------- | -------- |
|  
![Screenshot (21)](https://github.com/harry-olabs/avi-hub/assets/80858126/a5656330-78e8-446f-b55a-58a13db890d5)
  |  
![Screenshot (34)](https://github.com/harry-olabs/avi-hub/assets/80858126/fe40818a-2311-4a59-8b92-b229139760d4)
  |

2023-06-14 09:37 UTC, harry-olabs requested changes

2023-06-14 09:37 UTC, harry-olabs commented on template/dashboard.html
> +    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
Consider adding fonts for bold (:600,700,800,900)

2023-06-14 09:37 UTC, harry-olabs commented on template/styles/dashboard.css
> +}
Reset some general style for all elements:

```css
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
```

2023-06-14 09:37 UTC, harry-olabs commented on template/styles/dashboard.css
> +.navbar {
Let there be an empty line between each style block. Do the same everywhere

2023-06-14 09:37 UTC, harry-olabs commented on template/styles/dashboard.css
> +}  */
This must be a typo, remove it.

```suggestion
} 
```

2023-06-14 09:37 UTC, harry-olabs commented on template/styles/dashboard.css
> +
Avoid leaving empty space at the end of each block

2023-06-14 09:37 UTC, harry-olabs commented on template/styles/dashboard.css
> +  }
This is not properly formatted. Correct the indentation

2023-06-14 09:37 UTC, harry-olabs commented on template/styles/dashboard.css
> +  }
This is not properly formatted. Correct indentation everywhere

2023-06-14 09:37 UTC, harry-olabs commented on template/styles/dashboard.css
> + /* box-shadow: 0 4px 8px rgba(0, 0, 0, 0.7); */
Remove if not used

2023-06-14 09:37 UTC, harry-olabs commented on template/styles/dashboard.css
> + /* background-color:  rgb(248, 244, 244); */
Remove if not used

2023-06-14 09:37 UTC, harry-olabs commented on template/styles/dashboard.css
> +} */
Remove if not used

2023-06-14 09:37 UTC, harry-olabs commented on template/dashboard.html
> +                  <h4><b>John Doe</b></h4>
You don't need to wrap the text with `<b>` tag, make use of css to make the font bold.

2023-06-14 09:37 UTC, harry-olabs commented on template/dashboard.html
> +                            <h3><b>Welcome John</b></h3>
The same applies here. Make use of css to make the font bold.

2023-06-14 09:37 UTC, harry-olabs commented on template/dashboard.html
> +                        <h3><b>Employee Structure</b></h3>
The same applies here. Make use of css to make the font bold.

2023-06-14 14:14 UTC, Doyin02 commented
## This is the updated styles for the dashboard UI template 
![Screenshot (41)](https://github.com/harry-olabs/avi-hub/assets/80858126/a77f7306-605b-4c6b-830e-c9644216b9ad)

2023-06-15 09:20 UTC, harry-olabs commented on template/styles/dashboard.css
> +  margin:0;
@Doyin02 why did you exclude `box-sizing: border-box`?

2023-06-15 09:20 UTC, harry-olabs commented on template/styles/dashboard.css
> +*{
There should be space after the astericks.

2023-06-15 09:20 UTC, harry-olabs commented on template/styles/dashboard.css
> +
I did mention in a previous comment, avoid empty space at the end of the closing block

2023-06-15 09:20 UTC, harry-olabs commented on template/styles/dashboard.css
> +
Remove empty line

2023-06-15 09:20 UTC, harry-olabs commented on template/styles/dashboard.css
> +.navbar__left-logo img{
Let there be an empty line after each block. Go over each style block and space out each block.

2023-06-15 09:51 UTC, Doyin02 commented on template/styles/dashboard.css
> +  margin:0;
I have already included it

2023-06-15 18:24 UTC, harry-olabs requested changes

2023-06-15 18:24 UTC, harry-olabs commented on template/styles/dashboard.css
> +  outline: 1px dashed red;
This is no longer required. Remove it 🔥

2023-06-15 18:33 UTC, Doyin02 commented
already removed the style that wasn't needed.

2023-06-15 19:11 UTC, harry-olabs approved these changes

2023-06-15 19:13 UTC, merged