AVI-18: Implement the login page
harry-olabs/avi-hub pull request #23
Opened 2023-06-28 14:42 UTC by Doyin02

### What does this PR do

This is the login page implemented with React

Closes #18

### How should it be tested

- Go to your local development
- Note: Inside the the component folder, you will find re-usable components (Button and Input)
- Note: Also inside the feature folder, you will find the login page built with react.
- Open the terminal, and launch the REACT app with npm or yarn start.

2023-07-11 12:20 UTC, harry-olabs commented
@Doyin02 work on the following:

- Remove the scale effect on the login form card when hovered
- Remove the scale(0.9), it is not needed
- Update the login form input padding to 14px
- I see you styled the `body` in the login scss file, it might overlap and effect the styling for other pages. You avoid doing that. Instead, make use of a container/wrapper, then style the container.
- When I click on the login button, I don't get redirected to the Dashboard page.

2023-07-11 12:56 UTC, harry-olabs requested changes
@Doyin02 It is almost looking good. Attend to the following requested changes

2023-07-11 12:56 UTC, harry-olabs commented on src/App.js
> +  </Routes>
Move this to a dedicated route file

2023-07-11 12:56 UTC, harry-olabs commented on src/App.js
> +);
This must be typo, remove it

2023-07-11 12:56 UTC, harry-olabs commented on src/components/Button/Button.css
> +}
Apply proper formatting to this stylesheet

2023-07-11 12:56 UTC, harry-olabs commented on src/components/Input/Input.css
> +}
Let there be space (empty line) after each style block 🔥

2023-07-11 12:56 UTC, harry-olabs commented on src/components/Button/index.jsx
> +    <button className='button'>{text}</button>
Make use of a custom-class name (e.g `custom-btn`) as opposed to generic name `button`.

2023-07-11 12:56 UTC, harry-olabs commented on src/components/Button/index.jsx
> +    <button className='button'>{text}</button>
A button should ideally have an `onClick` handler prop. Be sure to add it

2023-07-11 12:56 UTC, harry-olabs commented on src/components/Input/index.jsx
> +    }
Move this to a function, then execute the function within the handleChange.

2023-07-11 12:56 UTC, harry-olabs commented on src/feature/Login/Login.module.css
> +  font-family: "Montserrat", sans-serif;
We have variable for this, make use of it.

2023-07-11 12:56 UTC, harry-olabs commented on src/feature/Login/index.jsx
> +          <Link to="/Registration" className={styles.register__link__anchor}>Register</Link>
Route path should be in lowercase. And for multiple words, make use hyphen to separate the words (e.g `my-profile`).

2023-07-11 12:56 UTC, harry-olabs commented on src/index.js
> +   <BrowserRouter><App/></BrowserRouter>
Format this properly to improve readability

2023-07-11 12:56 UTC, harry-olabs commented on template/login.html
You shouldn't have to touch this file. All you need to do was to copy the codes you need.

— **IMPORTANT**: Never remove anything from the template files unless you want update the UI template.

2023-07-17 19:15 UTC, harry-olabs requested changes
@Doyin02 we are almost there. Attend to the comments.

**IMPORTANT**: Don't forget to mark a comment as resolved whenever you resolve it.

2023-07-17 19:15 UTC, harry-olabs commented on src/feature/Login/index.jsx
> +          <Link to="/Registration" className={styles.register__link__anchor}>Register</Link>
The class name `register__link__anchor` should ideally be `login_link...`

2023-07-17 19:15 UTC, harry-olabs commented on src/components/Button/Button.css
> +}
This should not be here, but rather in the root level like `index.css` file — Remove it.

2023-07-17 19:15 UTC, harry-olabs commented on src/components/Button/index.jsx
> +const Button = ({ to, text, handleClick }) => {
The `to` prop is not used. Remove it

2023-07-17 19:15 UTC, harry-olabs commented on src/components/Input/Input.css
> +}
I've commented about this up top, remove it 🔥

2023-07-17 19:15 UTC, harry-olabs commented on src/components/Main-styles/variables.css
- Move this to the root, preferably in a `styles` folder.
- Also, I don't see the `variables.css` file in the template styles folder anymore. Did you remove it? If so, put it back.

2023-07-17 19:15 UTC, harry-olabs commented on src/components/Main-styles/main.css
Move this to the root, preferably in a `styles` folder.

2023-07-17 19:15 UTC, harry-olabs commented on src/App.js
> +
This is not formatted properly, correct it

2023-07-17 19:21 UTC, harry-olabs commented on src/feature/Login/index.jsx
> +          <Link to="/Registration" className={styles.register__link__anchor}>Register</Link>
Reach out if you don't understand what you're expected to do here

2023-07-17 19:29 UTC, Doyin02 commented on src/components/Main-styles/variables.css
when I tried to access the varable.css file from the react app, it gave an error that it cannot access any file that is outside of the src folder, that was why I brought it inside the src folder

2023-07-17 19:32 UTC, harry-olabs commented on src/components/Main-styles/variables.css
You are not expected to make use of the `variables.css` file in the template folder.

2023-07-17 19:34 UTC, Doyin02 commented on src/components/Main-styles/variables.css
How am I going to access the styles in there

2023-07-17 19:34 UTC, harry-olabs commented on src/components/Main-styles/variables.css
Like I mentioned in a previous comment, don't move or delete anything in the templates folder. You can only reference the codes/styles

2023-07-17 19:37 UTC, Doyin02 commented on src/components/Main-styles/variables.css
I don't understand sir, the components brought out an error when I wanted to access the variable.css, it said I cannot access anything outside the src folder, what am I supposed to do?

2023-07-17 21:28 UTC, harry-olabs commented on src/components/Main-styles/variables.css
@Doyin02 
- Firstly, keep this `variables.css` file, but be sure to move it to the root in `styles` folder.
- Secondly, put back the `variables.css` file in the template styles folder.

2023-07-18 06:45 UTC, Doyin02 commented on src/components/Main-styles/variables.css
Do yo mean I can leave the variable.css file that is inside the Main styles folder, but I should just move the variable.css to the styles also?

2023-07-18 14:20 UTC, harry-olabs requested changes
@Doyin02 It's almost looking good, attend to the comments

2023-07-18 14:20 UTC, harry-olabs commented on src/components/Button/Button.css
> +  background-color: #4caf50;
Replace color value with variable

2023-07-18 14:20 UTC, harry-olabs commented on src/components/Button/Button.css
> +  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
I believe there is a variable for box-shadow, make use of it

2023-07-18 14:20 UTC, harry-olabs commented on src/components/Input/Input.css
> +  background-color: #f2f2f2;
Make use of variable

2023-07-18 14:20 UTC, harry-olabs commented on src/components/Input/Input.css
> +  background-color: #e0e0e0;
Make use of variable

2023-07-18 14:20 UTC, harry-olabs commented on src/components/Input/Input.css
> +  color: rgb(72, 68, 68);
Make use of variable

2023-07-18 14:20 UTC, harry-olabs commented on src/feature/Login/Login.module.css
> +  background: linear-gradient(135deg, #00f260, #0575e6);
Make use of variable

2023-07-18 14:20 UTC, harry-olabs commented on src/feature/Login/Login.module.css
> +  background-color: #f2f2f2;
Make use of variable

2023-07-18 14:20 UTC, harry-olabs commented on src/feature/Login/Login.module.css
> +  background-color: #e0e0e0;
Make use of variable

2023-07-18 14:20 UTC, harry-olabs commented on src/feature/Login/Login.module.css
> +  color: #333;
Make use of variable

2023-07-18 14:20 UTC, harry-olabs commented on src/feature/Login/Login.module.css
> +  color: #333;
Make use of variable

2023-07-18 14:20 UTC, harry-olabs commented on src/index.css
> +  font-family: "Montserrat", sans-serif;
You are supposed to make use of `--font-family` variable. Correct this

2023-07-18 14:20 UTC, harry-olabs commented on src/index.css
>  }
You can remove this style block, it is not used

2023-07-18 14:20 UTC, harry-olabs commented on src/styles/variables.css
> +  --primary-black:black;
Format properly (space after colon)

2023-07-19 08:25 UTC, harry-olabs approved these changes
LGTM 🚀

2023-07-19 08:26 UTC, merged