AVI-39: User Authentication | Implement signup functionality
harry-olabs/avi-hub pull request #42
Opened 2023-09-07 18:29 UTC by Doyin02

### What does this PR do

 Implemented user signup functionality using React and Redux on the front end.
 Utilized access tokens for secure user authentication
 Improved error handling for signup, including validation checks and informative error messages.

Closes #39

### How should it be tested

Spin up the app in dev mode with npm start
Head over to the registration 

### Screenshots

![Screenshot (197)](https://github.com/harry-olabs/avi-hub/assets/80858126/880c8da2-51a8-42b4-98d0-dbc2844fc6a6)

2023-09-13 07:21 UTC, harry-olabs requested changes
@Doyin02 it is looking good, and some adjustments. Attend to the comments

2023-09-13 07:21 UTC, harry-olabs commented on src/feature/Registration/index.jsx
> +      }, 3000);
Can you explain why we setting a timeout if we only need to show error alert?

2023-09-13 07:21 UTC, harry-olabs commented on src/feature/Registration/index.jsx
> +      console.error("Error:", error);
Do not keep console log statement in code. Remove it

2023-09-13 07:21 UTC, harry-olabs commented on src/feature/Registration/index.jsx
> +        console.log(response);
Do not keep console log statement in code. Remove it

2023-09-13 07:21 UTC, harry-olabs commented on src/index.js
> +import store from "../src/redux/store";
Why did you traverse outside the `src` folder?
Isn't this supposed to be

```suggestion
import store from "./redux/store";
```

2023-09-13 07:21 UTC, harry-olabs commented on src/redux/actionTypes.js
The same way you have an `actions` folder, create a `types` folder with every action type files.
For example:
```
redux/types/auth-type.js
```

2023-09-13 07:21 UTC, harry-olabs commented on src/redux/actions/authActions.js
For the file name, use the naming convention with hyphen
For example:
```
auth-actions.js
```

2023-09-13 07:21 UTC, harry-olabs commented on src/redux/rootReducer.js
> +export default rootReducer;
Create an `index.js` file in the `reducers` folder and move this codes in there

2023-09-13 14:14 UTC, Doyin02 commented on src/redux/actionTypes.js
I don't understand sir

2023-09-15 10:07 UTC, harry-olabs commented on src/redux/store.js
> +});
This is already already defined in the `reducers/index` file — remove it 🔥

2023-09-15 10:07 UTC, harry-olabs commented on src/utils/validation.js
> +  };
Format this properly

2023-09-15 10:09 UTC, harry-olabs commented on src/App.js
> +import 'bootstrap/dist/js/bootstrap.min.js';
Why don't you add this to the `src/index.css` file instead?

2023-09-15 13:41 UTC, harry-olabs requested changes

2023-09-15 13:41 UTC, harry-olabs commented on src/feature/Registration/index.jsx
> +        const data = await response.json();
Start adopting custom hooks for http requests and services.
Follow this tutorial to refactor this into a custom hook `useFetch`.

https://blog.openreplay.com/building-a-custom-fetch-hook-in-react/#:~:text=Building%20the%20custom%20Fetch%20Hook&text=You%20can%20name%20the%20hook,are%20fetching%20the%20data%20from.

2023-09-15 13:41 UTC, harry-olabs commented on src/feature/Registration/index.jsx
>    const [confirmPassword, setConfirmPassword] = useState("");
Refactor this into a single state:

```suggestion
  const signupForm = useState({
    firstName: '',
    lastName: '',
    email: '',
    password: '',
    confirmPassword: '',
  });
```

For each input element, give it the matching name key. For example:
```
<input name="firstName" onChange={setFormValue} />
```

Then to update form value, simple do:

```js
const setFormValue = (el) => {
    setSignupForm(form => ({
      ...form,
      [el.target.name]: el.target.value
    }))
  }
```

After these, clean up the code to remove all the repetative handleChange function.

2023-09-25 09:48 UTC, harry-olabs requested changes
It is looking good, just minor chanages

2023-09-25 09:48 UTC, harry-olabs commented on src/feature/Registration/index.jsx
> +  const [state, setState] = useState({
Use name like `formData` and `setFormData` instead.

2023-09-25 09:48 UTC, harry-olabs commented on src/hooks/use-fetch-bak.js
This is a duplicate file and is not being used? Delete file

2023-09-26 10:52 UTC, harry-olabs approved these changes

2023-09-26 10:53 UTC, merged